## LAB | Prompt Engineering Lab

You've been hired as an AI consultant by TechFlow Solutions, a company that's struggling with their customer service chatbot. The chatbot is producing inconsistent, unreliable responses that are frustrating customers and hurting the company's reputation. Your task is to diagnose the problems with their current prompts and systematically improve them using professional prompt engineering techniques.

### Part 1: Starting Simple - Create Initial Prompts

#### Step 1: Setup Your Environment

In [1]:
import os
from concurrent.futures import ThreadPoolExecutor

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from openai import OpenAI

# OpenAI client setup
client = OpenAI()
MODEL = os.getenv("OPENAI_MODEL", "gpt-5.4-mini")


def run_prompt(prompt, model=MODEL):
    """Send one prompt to the OpenAI Responses API and return plain text."""
    response = client.responses.create(
        model=model,
        input=prompt,
    )
    return response.output_text.strip()


def run_prompts_parallel(prompts, model=MODEL, max_workers=5):
    """Run multiple prompts concurrently and return results in the same order."""
    prompts = list(prompts)
    if not prompts:
        return []

    workers = min(max_workers, len(prompts))
    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = [executor.submit(run_prompt, prompt, model) for prompt in prompts]
        return [future.result() for future in futures]


# Smoke test for the checkpoint
_ = run_prompt("Reply with exactly: Setup complete")
print("Setup complete")

Setup complete

#### Step 2: Create Initial Prompts

In [2]:
# Task 1: Sentiment Analysis

# Initial simple prompt for sentiment analysis
sentiment_prompt_v1 = """
Classify this customer message: "I love this product! It's exactly what I needed."
"""
 
# Test it once
result = run_prompt(sentiment_prompt_v1)
print("Sentiment Analysis Result:")
print(result)

Sentiment Analysis Result:
Positive

In [3]:
# Task 2: Product Description Generation

# Initial simple prompt for product description
product_prompt_v1 = """
Create a product description for a wireless mouse that costs $29.99.
"""
 
# Test it once
result = run_prompt(product_prompt_v1)
print("Product Description Result:")
print(result)

Product Description Result:
Meet the Wireless Mouse, designed for smooth, reliable performance at an affordable price of just **$29.99**. With a comfortable ergonomic shape and responsive tracking, it’s ideal for work, school, or everyday use.

**Features:**
- **Wireless convenience** for a clutter-free setup
- **Smooth, accurate tracking** for easy navigation
- **Comfortable design** for all-day use
- **Simple plug-and-play setup**
- **Great value** at only **$29.99**

Whether you're upgrading your desk or need a dependable mouse on the go, this wireless mouse delivers everyday performance without the hassle of cords.

In [4]:
# Task 3: Data Extraction

# Initial simple prompt for data extraction
extraction_prompt_v1 = """
Extract information from this customer feedback: "I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged."
"""
 
# Test it once
result = run_prompt(extraction_prompt_v1)
print("Data Extraction Result:")
print(result)

Data Extraction Result:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged

### Part 2: Diagnosing Failures - Systematic Testing

#### Step 3: Run Prompts 5 Times

In [5]:
from collections import defaultdict
import pandas as pd

def run_prompt_n_times(prompt, n=5, model=MODEL):
    """Run the same prompt multiple times and return all outputs."""
    return [run_prompt(prompt, model=model) for _ in range(n)]

def test_prompts_5_times(prompt_dict, n=5, model=MODEL):
    """
    prompt_dict format:
    {
        "sentiment": "prompt text",
        "classification": "prompt text",
        "summary": "prompt text"
    }
    """
    results = defaultdict(list)

    for name, prompt in prompt_dict.items():
        results[name] = run_prompt_n_times(prompt, n=n, model=model)

    return results

# Example prompts from your lab
prompt_dict = {
    "sentiment": sentiment_prompt_v1,
    "product": product_prompt_v1,
    "extraction": extraction_prompt_v1
}

results = test_prompts_5_times(prompt_dict, n=5)

for task, outputs in results.items():
    print(f"\n=== {task.upper()} ===")
    for i, output in enumerate(outputs, start=1):
        print(f"Run {i}: {output}")

=== SENTIMENT ===
Run 1: Positive
Run 2: Positive
Run 3: **Classification:** Positive / Praise

The customer is expressing satisfaction and appreciation for the product.
Run 4: Sentiment: **Positive**
Run 5: positive

=== PRODUCT ===
Run 1: Upgrade your everyday computing with this sleek wireless mouse, designed for comfort, precision, and convenience. Its responsive tracking and reliable wireless connection help you work and browse with ease, while the ergonomic shape fits naturally in your hand for all-day use.

At just **$29.99**, it’s an affordable way to add smooth performance and clutter-free control to your desk. Compact, dependable, and easy to set up, this wireless mouse is a smart choice for home, office, or on-the-go use.
Run 2: Meet the sleek Wireless Mouse, designed for smooth everyday performance at just **$29.99**. With reliable wireless connectivity, comfortable ergonomic shaping, and precise cursor control, it’s a great choice for work, study, or casual browsing.

**Highlights:**
- **Wireless freedom** for a clutter-free setup
- **Comfortable design** for all-day use
- **Responsive tracking** for accurate navigation
- **Affordable price** at **$29.99**

Simple, dependable, and easy to use, this wireless mouse delivers the convenience you need without stretching your budget.
Run 3: Meet the Wireless Mouse, a sleek and reliable everyday essential designed to keep up with work, study, and entertainment. With smooth wireless connectivity, comfortable ergonomic shaping, and precise cursor control, it makes navigating your device effortless. Its compact, travel-friendly design fits easily in a bag or backpack, while the long-lasting battery helps you stay productive without constant recharging.

At just **$29.99**, this wireless mouse offers dependable performance and great value for home, office, or on the go.
Run 4: Meet the sleek, reliable wireless mouse designed for everyday comfort and effortless control — all for just **$29.99**. With smooth tracking, a responsive click feel, and a compact wireless design, it’s perfect for work, school, or travel.

### Key Features
- **Wireless freedom** for a clutter-free workspace
- **Comfortable ergonomic shape** for long-lasting use
- **Precise tracking** for accurate navigation
- **Easy plug-and-play setup** with no complicated installation
- **Portable and lightweight** for use at home or on the go

Whether you’re browsing, working on projects, or gaming casually, this wireless mouse delivers dependable performance at an affordable price.
Run 5: Meet the **Wireless Mouse for $29.99** — a reliable, comfortable, and affordable everyday essential for work, school, or home use.

Designed for smooth navigation and effortless control, this wireless mouse offers a clutter-free experience with responsive tracking and easy plug-and-play setup. Its ergonomic shape fits naturally in your hand, helping reduce strain during long hours of use. Compact and lightweight, it’s also easy to carry in a laptop bag or backpack.

**Features:**
- Wireless connectivity for a clean, cable-free workspace
- Comfortable ergonomic design
- Smooth and accurate cursor control
- Compact, portable, and easy to use
- Great value at just **$29.99**

Whether you’re upgrading your desk setup or need a dependable mouse on the go, this wireless mouse delivers convenience, comfort, and performance at a great price.

=== EXTRACTION ===
Run 1: Here’s the extracted information from the feedback:

- **Order/item number:** 12345
- **Order date:** March 15th
- **Delivery experience:** Fast
- **Packaging issue:** Damaged packaging
Run 2: Here’s the extracted information:

- **Order item number:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged
Run 3: Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging:** Damaged
Run 4: Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged
Run 5: Here’s the extracted information:

- **Order/item ID:** #12345
- **Order date:** March 15th
- **Delivery sentiment:** Fast
- **Packaging issue:** Damaged packaging

If you want, I can also format this as structured JSON or a table.

In [6]:
for task, outputs in results.items():
    unique_outputs = len(set(outputs))
    print(f"{task}: {unique_outputs}/5 unique responses")

sentiment: 4/5 unique responses
product: 5/5 unique responses
extraction: 5/5 unique responses

**Observations:** We can see that the vast majority of outputs are unique, 13/15 or 86.66%. We can also assess that repetitions only take place in the sentiment outputs, and that sentiment analysis and data extraction do not vary greatly content-wise, the changes are merely simple format differences, as expected. For product description generation instead we do see that content varies and the tool gets creative. Some decide to show the features and have more sober catching phrases without mentionning features like Run 3, or more intense and cumbersome as Run 4, which could be classified as different marketing perspectives.

#### Step 4: Run Prompts 10 Times

In [7]:
import pandas as pd

prompts = {
    "sentiment": sentiment_prompt_v1,
    "product_description": product_prompt_v1,
    "data_extraction": extraction_prompt_v1,
}

def run_prompt_n_times(prompt, n=10, model=MODEL):
    return [run_prompt(prompt, model=model) for _ in range(n)]

results_5 = {name: run_prompt_n_times(prompt, n=5) for name, prompt in prompts.items()}
results_10 = {name: run_prompt_n_times(prompt, n=10) for name, prompt in prompts.items()}

rows = []

for name in prompts:
    for i, output in enumerate(results_10[name], start=1):
        rows.append({
            "prompt": name,
            "test_size": 10,
            "run": i,
            "response": output
        })

df = pd.DataFrame(rows)

# Display the full table for better readability
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.max_rows", None)

df

,prompt,test_size,run,response
0,sentiment,10,1,Positive
1,sentiment,10,2,positive
2,sentiment,10,3,**Sentiment:** Positive
3,sentiment,10,4,**Positive**
4,sentiment,10,5,Positive
5,sentiment,10,6,Positive
6,sentiment,10,7,Positive
7,sentiment,10,8,**Sentiment:** Positive \n**Category:** Praise / Satisfaction
8,sentiment,10,9,Positive
9,sentiment,10,10,Positive
10,product_description,10,1,"Meet the sleek, reliable wireless mouse designed to keep up with your day. At just **$29.99**, it delivers smooth tracking, comfortable all-day use, and a clutter-free setup without the hassle of cords. Its compact, ergonomic design fits naturally in your hand, making it a great choice for work, school, or travel.\n\nEnjoy responsive performance, easy plug-and-play setup, and dependable wireless connectivity that helps you stay productive wherever you are. Whether you’re browsing, editing, or multitasking, this wireless mouse offers the convenience and comfort you need at a great value."
11,product_description,10,2,"Experience smooth, reliable control with this sleek wireless mouse, priced at just **$29.99**. Designed for everyday productivity, it offers a comfortable ergonomic fit, responsive tracking, and a clutter-free wireless connection that keeps your workspace clean and efficient. \n\nWhether you’re working from home, studying, or on the go, this mouse delivers dependable performance with easy setup and long-lasting convenience. \n\n**Highlights:**\n- **Price:** $29.99\n- Wireless connectivity for a tidy workspace\n- Comfortable design for all-day use\n- Precise cursor control for work and browsing\n- Compact and portable for travel\n\nA simple, affordable upgrade that makes everyday computing easier."
12,product_description,10,3,"Meet the Wireless Mouse designed for smooth, reliable everyday performance at an affordable price of just **$29.99**. With a comfortable ergonomic shape, precise tracking, and a clutter-free wireless connection, it’s a great fit for work, study, or home use.\n\n**Features:**\n- **$29.99 price**\n- Wireless connectivity for easy, cable-free use\n- Comfortable design for all-day handling\n- Responsive tracking for accurate cursor control\n- Compact and portable for use anywhere\n\nSimple, dependable, and budget-friendly, this wireless mouse delivers the convenience you need without breaking the bank."
13,product_description,10,4,"Meet the **Wireless Mouse** designed for smooth, reliable everyday use—all for just **$29.99**.\n\nEnjoy a clutter-free workspace with responsive wireless connectivity, comfortable ergonomics, and precise tracking for work, school, or browsing. Its compact, lightweight design makes it easy to take anywhere, while the long-lasting battery helps keep you productive without constant interruptions.\n\n**Features:**\n- Reliable wireless connection\n- Comfortable, easy-to-hold design\n- Smooth and accurate cursor control\n- Portable and lightweight\n- Great for home, office, or travel\n\nSimple, practical, and affordable—this wireless mouse delivers the performance you need at a price you’ll love."
14,product_description,10,5,"Meet the Wireless Mouse, a sleek and reliable everyday essential designed to keep you moving smoothly and comfortably. With responsive tracking, a compact wireless connection, and an ergonomic shape that fits naturally in your hand, it’s ideal for work, home, or travel.\n\nEnjoy clutter-free convenience with easy plug-and-play setup and dependable performance across your favorite tasks. Whether you’re scrolling through documents, browsing the web, or tackling a busy workday, this mouse delivers precision and comfort at an affordable price.\n\n**Price: $29.99**"
15,product_description,10,6,"Meet the Wireless Mouse, a sleek and reliable everyday essential designed to keep up with your work, study, and browsing needs. With a comfortable ergonomic shape and smooth wireless connectivity, it delivers precise control without the clutter of cords.\n\nPerfect for home, office, or travel, this mouse offers easy plug-and-play setup, responsive tracking, and a long-lasting battery for dependable performance throughout the day. Its compact design fits naturally in your hand and slips easily into a laptop bag or backpack.\n\n**Price: $29.99**\n\nA simple, affordable upgrade for anyone who wants comfort, convenience, and dependable performance in one compact device."
16,product_description,10,7,"Experience smooth, reliable control with this wireless mouse, designed for everyday productivity and comfort. Its responsive tracking and ergonomic shape make it easy to work, browse, and navigate for hours without strain. With a simple plug-and-play wireless connection, setup is quick and hassle-free.\n\nCompact and portable, this mouse is perfect for home, office, or travel use. Enjoy dependable performance, convenient wireless freedom, and a clean, clutter-free workspace—all for just **$29.99**."
17,product_description,10,8,"Meet the **Wireless Mouse** designed for smooth, reliable everyday use—all for just **$29.99**.\n\nEnjoy **wire-free convenience**, **responsive tracking**, and a **comfortable ergonomic shape** that fits naturally in your hand. Whether you're working, browsing, or gaming casually, this mouse delivers dependable performance with minimal setup and maximum ease.\n\n**Features:**\n- Wireless connectivity for clutter-free desk space\n- Smooth, accurate cursor control\n- Comfortable design for extended use\n- Compact and portable for work on the go\n- Easy plug-and-play setup\n\nUpgrade your workspace with a practical, affordable mouse that keeps up with your day. \n**Price: $29.99**"
18,product_description,10,9,"Experience smooth, reliable control with this wireless mouse priced at just **$29.99**. Designed for everyday comfort and convenience, it features a sleek ergonomic shape, responsive tracking, and a clutter-free wireless connection that helps keep your workspace organized.\n\n**Key features:**\n- **Wireless freedom** for easy, cable-free use\n- **Comfortable ergonomic design** for all-day handling\n- **Precise cursor control** for work, browsing, and more\n- **Compact and portable** for home, office, or travel\n- **Great value at $29.99**\n\nWhether you're upgrading your desk setup or need a dependable mouse on the go, this wireless mouse delivers simple performance and everyday comfort at an affordable price."
19,product_description,10,10,"Meet the Wireless Mouse, designed for smooth, reliable performance at an affordable price of **$29.99**. Whether you’re working, browsing, or studying, this sleek mouse delivers comfortable control with responsive tracking and a clutter-free wireless connection.\n\n**Features:**\n- Wireless convenience for a clean, cable-free setup\n- Comfortable ergonomic design for everyday use\n- Precise cursor control for productivity and navigation\n- Compact and portable for home, office, or travel\n- Easy plug-and-play setup\n\nSimple, stylish, and dependable, this wireless mouse is a great everyday essential for just **$29.99**."
20,data_extraction,10,1,"Here’s the extracted information from the feedback:\n\n- **Order/item number:** 12345\n- **Order date:** March 15th\n- **Delivery experience:** Fast\n- **Packaging issue:** Damaged packaging\n\nIf you want, I can also convert this into a structured JSON format."
21,data_extraction,10,2,"Here’s the extracted information:\n\n- **Order item:** `#12345`\n- **Order date:** `March 15th`\n- **Delivery feedback:** `Fast`\n- **Packaging feedback:** `Damaged`\n\nIf you want, I can also format this as JSON or a table."
22,data_extraction,10,3,"Here’s the extracted information:\n\n- **Order item:** #12345\n- **Order date:** March 15th\n- **Delivery experience:** Fast\n- **Packaging issue:** Damaged\n\nIf you want, I can also format this as JSON or a structured table."
23,data_extraction,10,4,"Here’s the extracted information:\n\n- **Order item:** #12345\n- **Order date:** March 15th\n- **Delivery feedback:** Fast\n- **Packaging feedback:** Damaged\n\nIf you'd like, I can also format this as JSON or a structured table."
24,data_extraction,10,5,Here’s the extracted information:\n\n- **Order item:** #12345 \n- **Order date:** March 15th \n- **Delivery feedback:** Fast \n- **Packaging feedback:** Damaged
25,data_extraction,10,6,Here’s the extracted information:\n\n- **Order/item number:** 12345 \n- **Order date:** March 15th \n- **Delivery experience:** Fast \n- **Packaging condition:** Damaged
26,data_extraction,10,7,Here’s the extracted information from the feedback:\n\n- **Item ID:** 12345\n- **Order Date:** March 15th\n- **Delivery Experience:** Fast\n- **Packaging Condition:** Damaged
27,data_extraction,10,8,Here’s the extracted information:\n\n- **Order item:** #12345 \n- **Order date:** March 15th \n- **Delivery feedback:** Fast \n- **Packaging feedback:** Damaged
28,data_extraction,10,9,"Here’s the extracted information:\n\n- **Order item:** #12345\n- **Order date:** March 15th\n- **Delivery:** Fast\n- **Packaging:** Damaged\n\nIf you want, I can also convert this into JSON or a structured table."
29,data_extraction,10,10,Here’s the extracted information:\n\n- **Order/item number:** 12345\n- **Order date:** March 15th\n- **Delivery feedback:** Fast\n- **Packaging feedback:** Damaged

#### Step 5: Run Prompts 15 Times and Create Failure Analysis

In [8]:
import pandas as pd
from collections import Counter

# Step 5: Run Prompts 15 Times and Create Failure Analysis

prompts = {
    "sentiment": sentiment_prompt_v1,
    "product_description": product_prompt_v1,
    "data_extraction": extraction_prompt_v1,
}

def run_prompt_n_times(prompt, n=15, model=MODEL):
    return [run_prompt(prompt, model=model) for _ in range(n)]

results_15 = {
    name: run_prompt_n_times(prompt, n=15)
    for name, prompt in prompts.items()
}

rows = []

for name, outputs in results_15.items():
    counts = Counter(outputs)
    total_runs = len(outputs)
    unique_responses = len(counts)
    most_common_response, most_common_count = counts.most_common(1)[0]
    consistency_pct = round((most_common_count / total_runs) * 100, 1)

    rows.append({
        "prompt": name,
        "total_runs": total_runs,
        "unique_responses": unique_responses,
        "consistency_pct": consistency_pct,
        "most_common_response": most_common_response,
    })

failure_analysis_df = pd.DataFrame(rows)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

failure_analysis_df

,prompt,total_runs,unique_responses,consistency_pct,most_common_response
0,sentiment,15,9,33.3,Positive
1,product_description,15,15,6.7,"Meet the **Wireless Mouse**, designed for smooth everyday performance and effortless comfort. With a responsive connection, precise tracking, and a sleek ergonomic shape, it’s perfect for work, school, or casual browsing. Compact and easy to carry, this mouse delivers reliable wireless convenience without the clutter of cords.\n\n**Price:** **$29.99**"
2,data_extraction,15,10,33.3,Here’s the extracted information:\n\n- **Order item:** #12345 \n- **Order date:** March 15th \n- **Delivery feedback:** Fast \n- **Packaging feedback:** Damaged

In [9]:
# Printing the outputs to eyeball patterns
for prompt_name, outputs in results_15.items():
    print(f"\n{'=' * 20} {prompt_name.upper()} {'=' * 20}")
    for i, output in enumerate(outputs, start=1):
        print(f"\nRun {i}:\n{output}\n")

==================== SENTIMENT ====================

Run 1:
Positive


Run 2:
**Category:** Positive feedback / praise


Run 3:
The message is **positive sentiment**.


Run 4:
**Sentiment:** Positive


Run 5:
**Category:** Positive feedback / Praise


Run 6:
Positive sentiment


Run 7:
Positive sentiment


Run 8:
Positive


Run 9:
**Classification:** Positive feedback / praise


Run 10:
**Sentiment:** Positive
**Category:** Praise / Satisfaction


Run 11:
Positive


Run 12:
Positive


Run 13:
**Classification:** Positive sentiment / satisfied customer

The customer is expressing strong satisfaction and approval of the product.


Run 14:
**Sentiment:** Positive


Run 15:
Positive


==================== PRODUCT_DESCRIPTION ====================

Run 1:
Meet the **Wireless Mouse**, designed for smooth everyday performance and effortless comfort. With a responsive connection, precise tracking, and a sleek ergonomic shape, it’s perfect for work, school, or casual browsing. Compact and easy to carry, this mouse delivers reliable wireless convenience without the clutter of cords.

**Price:** **$29.99**


Run 2:
Upgrade your everyday setup with this sleek wireless mouse, designed for smooth, reliable performance at an affordable price. At just **$29.99**, it delivers comfortable ergonomics, precise tracking, and clutter-free convenience for work, school, or travel.

**Features:**
- Reliable wireless connection for hassle-free use
- Compact, comfortable design for all-day productivity
- Smooth cursor control for everyday tasks
- Easy plug-and-play setup
- Great value at **$29.99**

Whether you're working at your desk or on the go, this wireless mouse is a simple, stylish solution that keeps you moving efficiently.


Run 3:
Experience smooth, reliable control with this sleek wireless mouse, designed for everyday productivity and comfort. With a responsive sensor, easy plug-and-play setup, and a compact design that fits naturally in your hand, it’s perfect for work, study, or travel. Enjoy clutter-free convenience and dependable performance at an affordable price.

**Price:** $29.99


Run 4:
Meet the **Wireless Mouse**, designed for smooth everyday productivity and comfortable all-day use. With reliable wireless connectivity, precise tracking, and a compact ergonomic shape, it’s a great fit for work, study, or travel.

**Features:**
- Easy plug-and-play wireless setup
- Responsive cursor control for accurate navigation
- Comfortable, portable design
- Long battery life for dependable use

**Price:** **$29.99**

A simple, affordable upgrade for your desk or laptop setup.


Run 5:
Meet the Wireless Mouse, designed for smooth, reliable everyday use at an affordable price of **$29.99**. With a comfortable ergonomic shape, precise tracking, and clutter-free wireless connectivity, it’s a great fit for work, school, or home.

**Features:**
- Reliable wireless connection
- Comfortable, compact design
- Smooth and accurate cursor control
- Easy plug-and-play setup
- Great for laptops and desktops

Simple, stylish, and dependable, this wireless mouse delivers the convenience you need without the cables.


Run 6:
Meet the **Wireless Mouse**, designed for smooth, reliable performance at an affordable price of **$29.99**.

Enjoy the freedom of a clutter-free workspace with easy wireless connectivity, precise cursor control, and a comfortable design that fits naturally in your hand. Whether you're working, browsing, or on the go, this mouse delivers dependable performance for everyday use.

**Highlights:**
- Wireless convenience for a clean setup
- Responsive tracking for accurate navigation
- Comfortable, ergonomic feel
- Compact and portable design
- Great value at just **$29.99**

A simple, dependable mouse that helps you get more done—without the cord.


Run 7:
Meet the sleek wireless mouse that delivers smooth, reliable performance for work, study, or everyday browsing. Designed for comfort and convenience, it offers a responsive feel, easy setup, and clutter-free freedom without tangled cords.

At just **$29.99**, this wireless mouse is a smart, affordable upgrade for any desktop or laptop setup. Compact, portable, and built for all-day use, it’s the perfect blend of simplicity, style, and value.


Run 8:
Meet the **Wireless Mouse — $29.99**, a sleek, reliable everyday essential designed for smooth navigation and comfortable use. With a responsive wireless connection, precise tracking, and a compact ergonomic shape, it’s perfect for work, school, or travel. The easy plug-and-play setup lets you get started in seconds, while the long-lasting battery helps keep you moving without constant interruptions.

**Why you’ll love it:**
- Smooth, accurate cursor control
- Comfortable design for daily use
- Wireless freedom with simple setup
- Portable and lightweight
- Great value at just **$29.99**

A practical upgrade for any desk, this wireless mouse combines convenience, comfort, and performance in one affordable package.


Run 9:
Meet the **Wireless Mouse for $29.99** — a sleek, reliable everyday essential designed to keep up with your workflow, gaming, and browsing needs.

Enjoy **smooth, lag-free wireless performance** with easy plug-and-play setup, so you can get started in seconds. Its **ergonomic design** fits comfortably in your hand for extended use, while the **responsive buttons and precise tracking** make every click and scroll feel effortless.

**Features:**
- Reliable wireless connection
- Comfortable, ergonomic shape
- Precise cursor control
- Easy setup with a compact USB receiver
- Great for work, school, or home use

At just **$29.99**, this wireless mouse delivers convenience, comfort, and dependable performance without breaking the bank.


Run 10:
Meet the **Wireless Mouse** designed for everyday comfort, smooth performance, and clutter-free convenience—all for just **$29.99**.

Enjoy reliable wireless connectivity, responsive tracking, and an ergonomic shape that fits naturally in your hand for work, study, or browsing. With a compact, lightweight design, it’s easy to carry between home, office, or on the go.

**Features:**
- Wireless connection for a tidy, cable-free setup
- Comfortable, ergonomic design
- Smooth, accurate cursor control
- Portable and lightweight
- Great for laptops, desktops, and travel

Simple, practical, and affordable, this wireless mouse is a smart upgrade for any workspace.


Run 11:
Meet the Wireless Mouse, a sleek and reliable everyday essential priced at just **$29.99**. Designed for comfort and precision, it offers smooth tracking, responsive clicks, and clutter-free wireless convenience for work, study, or travel.

**Features:**
- Wireless connectivity for a tidy, cable-free setup
- Ergonomic design for comfortable all-day use
- Precise tracking for everyday tasks and browsing
- Compact and portable for easy travel
- Simple plug-and-play setup

Whether you're upgrading your workspace or need a dependable mouse on the go, this wireless mouse delivers performance and value at an affordable price.


Run 12:
Meet the **Wireless Mouse**, designed for smooth everyday use at just **$29.99**. With a reliable wireless connection, comfortable ergonomic shape, and precise tracking, it’s perfect for work, school, or home. Enjoy clutter-free convenience, easy portability, and dependable performance in a sleek, modern design.

**Features:**
- Wireless connectivity for a clean setup
- Comfortable grip for all-day use
- Accurate cursor control for productivity and browsing
- Compact and portable design
- Great value at **$29.99**


Run 13:
Meet the **Wireless Mouse for $29.99** — a sleek, reliable everyday essential designed to keep your workspace clutter-free and your workflow smooth. With responsive tracking, comfortable ergonomics, and easy wireless connectivity, it’s perfect for work, school, or casual browsing.

### Why you’ll love it:
- **$29.99 value** for dependable performance
- **Wireless freedom** with a clean, cable-free setup
- **Comfortable design** for all-day use
- **Responsive control** for accurate clicking and scrolling
- **Portable and lightweight** for use at home, in the office, or on the go

Simple, practical, and affordable, this wireless mouse delivers the convenience you need at a price you’ll appreciate.


Run 14:
Meet the **Wireless Mouse for $29.99** — a sleek, reliable everyday essential designed for smooth navigation and effortless productivity.

### Why you’ll love it
- **Wireless convenience:** Enjoy a clutter-free desk with stable wireless connectivity.
- **Comfortable design:** Ergonomically shaped for comfortable use throughout the day.
- **Responsive tracking:** Accurate cursor control for work, browsing, and light gaming.
- **Easy setup:** Plug in the compact receiver and start using it right away.
- **Portable and lightweight:** Perfect for home, office, or travel.

### Great for
- Daily office tasks
- Remote work setups
- Students and professionals
- On-the-go productivity

At just **$29.99**, this wireless mouse delivers dependable performance and everyday comfort at a great value.


Run 15:
Meet the **Wireless Mouse** built for smooth, reliable everyday use—all for just **$29.99**.

Designed for comfort and convenience, this mouse offers **cord-free freedom**, **responsive tracking**, and a **compact, travel-friendly design** that fits easily into your workspace or bag. Whether you’re working, studying, or browsing at home, it delivers dependable performance with easy setup and a clean, clutter-free desk.

### Key Features:
- **Wireless connectivity** for a tidy, hassle-free setup
- **Comfortable ergonomic design** for everyday use
- **Precise tracking** for smooth navigation
- **Portable and lightweight** for work on the go
- **Affordable price** at only **$29.99**

Simple, practical, and budget-friendly, this wireless mouse is a smart choice for anyone looking to upgrade their daily computing experience.


==================== DATA_EXTRACTION ====================

Run 1:
Here’s the extracted information:

- **Order/item number:** 12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 2:
Here’s the extracted information from the feedback:

- **Order/item number:** 12345
- **Order date:** March 15th
- **Delivery sentiment:** Fast
- **Packaging issue:** Damaged


Run 3:
Here’s the extracted information from the feedback:

- **Order item number:** 12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging condition:** Damaged


Run 4:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging:** Damaged

If you want, I can also convert this into a structured JSON format.


Run 5:
Here’s the extracted information from the feedback:

- **Order item number:** 12345
- **Order date:** March 15th
- **Delivery experience:** Fast
- **Packaging condition:** Damaged


Run 6:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 7:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 8:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 9:
Here’s the extracted information from the feedback:

- **Order item number:** 12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging condition:** Damaged


Run 10:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging issue:** Damaged


Run 11:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 12:
Here’s the extracted information from the feedback:

- **Item number:** 12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging:** Damaged


Run 13:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery:** Fast
- **Packaging:** Damaged


Run 14:
Here’s the extracted information:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery feedback:** Fast
- **Packaging feedback:** Damaged


Run 15:
Here’s the extracted information from the feedback:

- **Order item:** #12345
- **Order date:** March 15th
- **Delivery sentiment:** Fast
- **Packaging issue:** Damaged packaging

##### Failure patterns

**Sentiment:** Inconsistent formatting. Unnecessary categorization or overexplanation of the sentiment a consumer would not need. No hallucination or content variation.
#
**Product description:** Inconsistent formatting. Confusing price as features. Repetition of words in content. Length inconsistency. Inconsistent style
#
**Data extraction:** Inconsistent formatting. Adding commentary on what to do with the data. However pretty consistent fields name.

### Part 3: Iteration 1 - Rewriting Simple Prompts

#### Step 6: Improve Sentiment Analysis Prompt

In [10]:
# Task 1: Sentiment Analysis

# Initial simple prompt for sentiment analysis
sentiment_prompt_v2 = """
Classify this customer message: "I love this product! It's exactly what I needed."
The format should be: Sentiment: [Positive/Negative/Neutral]
2 words maximum for the output.
"""
 
# Test it once
result = run_prompt(sentiment_prompt_v2)
print("Sentiment Analysis Result:")
print(result)

Sentiment Analysis Result:
Sentiment: Positive

#### Step 7: Improve Product Description Prompt

In [11]:
# Task 2: Product Description Generation

# Initial simple prompt for product description
product_prompt_v2 = """
Create a product description for a wireless mouse that costs $29.99.
The format should be: 
[Product Description in sentences]
[3 Key Features in bullet points]
[2 Benefits in slogan style sentences]
These categories should not be labeled in the output, just formatted as described.
The description should be concise and highlight most important aspects. It should be no more than 2 sentences.
The style should be sober and persuasive, targeting tech-savvy consumers looking for affordable accessories.
The output should be no more than 30 words.
"""
 
# Test it once
result = run_prompt(product_prompt_v2)
print("Product Description Result:")
print(result)

Product Description Result:
Reliable wireless mouse for precise, clutter-free control at an affordable $29.99.
- 2.4GHz wireless connection
- Compact, ergonomic design
- Long battery life
Smooth tracking. Portable convenience.

#### Step 8: Improve Data Extraction Prompt:

In [12]:
# Task 3: Data Extraction

# Initial simple prompt for data extraction
extraction_prompt_v2 = """
Extract information from this customer feedback: "I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged."
The format should be:
- Order Number: [Extracted order number]
- Order Date: [Extracted order date]
- Delivery Feedback: [Extracted delivery feedback]
- Packaging Feedback: [Extracted packaging feedback]
All responses should start with a capital letter and be 2 words maximum.
There should be no additional text or labels, just the extracted information formatted as described.
"""
 
# Test it once
result = run_prompt(extraction_prompt_v2)
print("Data Extraction Result:")
print(result)

Data Extraction Result:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged

### Part 4: Iteration 2 - Adding Structure & Constraints

#### Step 9: Add Few-Shot Examples to Sentiment Analysis

In [13]:
import pandas as pd
from collections import Counter

# Run Prompt with Few-shot examples 15 Times and track consistency 

sentiment_prompt_v2 = """
Classify this customer message: "I love this product! It's exactly what I needed."
The format should be: Sentiment: [Positive/Negative/Neutral]
2 words maximum for the output.

Follow the examples below for formatting and style:

Example 1:
Sentiment: Positive

Example 2:
Sentiment: Negative

Example 3:
Sentiment: Neutral

Now classify the sentiment of the input provided. If none is provided, use the default example above.
"""

prompts = {
    "sentiment": sentiment_prompt_v2,
}

def run_prompt_n_times(prompt, n=15, model=MODEL):
    return [run_prompt(prompt, model=model) for _ in range(n)]

results_15 = {
    name: run_prompt_n_times(prompt, n=15)
    for name, prompt in prompts.items()
}

rows = []

for name, outputs in results_15.items():
    counts = Counter(outputs)
    total_runs = len(outputs)
    unique_responses = len(counts)
    most_common_response, most_common_count = counts.most_common(1)[0]
    consistency_pct = round((most_common_count / total_runs) * 100, 1)

    rows.append({
        "prompt": name,
        "total_runs": total_runs,
        "unique_responses": unique_responses,
        "consistency_pct": consistency_pct,
        "most_common_response": most_common_response,
    })

failure_analysis_df = pd.DataFrame(rows)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

failure_analysis_df

,prompt,total_runs,unique_responses,consistency_pct,most_common_response
0,sentiment,15,1,100.0,Sentiment: Positive

#### Step 10: Add Chain-of-Thought to Data Extraction

In [14]:

import pandas as pd
from collections import Counter

# Run Prompt with Few-shot examples 15 Times and track consistency 

extraction_prompt_v2 = """
Customer feedback: "I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged
You are a careful data extraction assistant.

Analyze the text step by step to identify all relevant facts, but only return the final extracted data in the exact format below.

- Order Number: [Extracted order number]
- Order Date: [Extracted order date]
- Delivery Feedback: [Extracted delivery feedback]
- Packaging Feedback: [Extracted packaging feedback]

All responses should start with a capital letter and be 2 words maximum.
There should be no additional text or labels, just the extracted information formatted as described.

Now extract information from the input provided.
"""

prompts = {
    "extraction": extraction_prompt_v2,
}

def run_prompt_n_times(prompt, n=15, model=MODEL):
    return [run_prompt(prompt, model=model) for _ in range(n)]

results_15 = {
    name: run_prompt_n_times(prompt, n=15)
    for name, prompt in prompts.items()
}

rows = []

for name, outputs in results_15.items():
    counts = Counter(outputs)
    total_runs = len(outputs)
    unique_responses = len(counts)
    most_common_response, most_common_count = counts.most_common(1)[0]
    consistency_pct = round((most_common_count / total_runs) * 100, 1)

    rows.append({
        "prompt": name,
        "total_runs": total_runs,
        "unique_responses": unique_responses,
        "consistency_pct": consistency_pct,
        "most_common_response": most_common_response,
    })

for i, output in enumerate(results_15["extraction"], start=1):
    print(f"\nRun {i}:\n{output}\n")

failure_analysis_df = pd.DataFrame(rows)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

failure_analysis_df

Run 1:
- Order Number: #12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 2:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 3:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 4:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 5:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 6:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 7:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 8:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 9:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 10:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 11:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 12:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 13:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 14:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged


Run 15:
- Order Number: 12345
- Order Date: March 15th
- Delivery Feedback: Fast
- Packaging Feedback: Damaged

,prompt,total_runs,unique_responses,consistency_pct,most_common_response
0,extraction,15,2,93.3,- Order Number: 12345\n- Order Date: March 15th\n- Delivery Feedback: Fast\n- Packaging Feedback: Damaged

#### Step 11: Add Few-Shot Examples and Structure to Product Description

In [15]:
# Add Few-Shot Examples and Structure to Product Description

product_prompt_v2 = """
You are a professional copywriter.

Create a product description for a wireless mouse that costs $29.99.
The format should be: 
[Product Description in sentences]
[3 Key Features in bullet points]
[2 Benefits in slogan style sentences]
These categories should not be labeled in the output, just formatted as described.
The description should be concise and highlight most important aspects. It should be no more than 2 sentences.
The style should be sober and persuasive, targeting tech-savvy consumers looking for affordable accessories.
The output should be no more than 40 words.

Follow the style of these examples:

Example 1:
Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.  
Smooth performance, effortless setup.

Example 2:
Wireless mouse for precise everyday control, priced at $29.99. Compact, smart, and built for efficient productivity.  

- Wireless connectivity  
- Ergonomic design  
- Long battery life  

Performance without clutter. Value without compromise.

Now write a product description for the input provided. If none is provided, use the default example above.
"""

# Test version 2 fifteen times
product_v2_results_15 = run_prompt_n_times(product_prompt_v2, n=15)

for i, output in enumerate(product_v2_results_15, start=1):
    print(f"\nRun {i}:\n{output}\n")

prompts = {
    "product": product_prompt_v2,
}

def run_prompt_n_times(prompt, n=15, model=MODEL):
    return [run_prompt(prompt, model=model) for _ in range(n)]

results_15 = {
    name: run_prompt_n_times(prompt, n=15)
    for name, prompt in prompts.items()
}

rows = []

for name, outputs in results_15.items():
    counts = Counter(outputs)
    total_runs = len(outputs)
    unique_responses = len(counts)
    most_common_response, most_common_count = counts.most_common(1)[0]
    consistency_pct = round((most_common_count / total_runs) * 100, 1)

    rows.append({
        "prompt": name,
        "total_runs": total_runs,
        "unique_responses": unique_responses,
        "consistency_pct": consistency_pct,
        "most_common_response": most_common_response,
    })

failure_analysis_df = pd.DataFrame(rows)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

failure_analysis_df

Run 1:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Smooth control, smart savings.


Run 2:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter. Value without compromise.


Run 3:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Value without compromise.


Run 4:
Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless connectivity
- Precise tracking
- Affordable value

Work smarter, spend less.
Smooth control, clean setup.


Run 5:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Run 6:
Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Budget-friendly value

Performance without clutter. Value without compromise.


Run 7:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Budget-friendly value

Performance without clutter.
Smooth control, smart savings.


Run 8:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and designed for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Smooth control, smart savings.


Run 9:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Smooth control, smart savings.


Run 10:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Run 11:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Run 12:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Value without compromise.


Run 13:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Value without compromise.


Run 14:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless connectivity
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Run 15:
Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Accurate tracking
- Affordable value

Performance without clutter.
Value without compromise.

,prompt,total_runs,unique_responses,consistency_pct,most_common_response
0,product,15,11,26.7,"Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.\n\n- Wireless connectivity\n- Accurate tracking\n- Affordable value\n\nPerformance without clutter. Value without compromise."

**Comparison of v3 with v1 results:**
#
v1 overall consistency: 18.8%
#
v3 overall consistency: 71,1%

In version 3 **sentiment and data extraction** resolved all failure patterns by reaching 1 unique response per prompt and 100% consistency
**product description** improved considerably, more than doubled consistency but we can still see the same failure patterns except for style inconsistency.

### Part 5: Tuning for Different Tasks

#### Step 12: Create Task Variations

In [16]:
# Create Task Variations

task_variations = {
    "sentiment": [
        "I love this product! It's exactly what I needed.",
        "This is okay, but I expected more.",
        "I'm really disappointed and want a refund.",
    ],
    "product_description": [
        "Create a product description for a wireless mouse that costs $29.99.",
        "Create a product description for a gaming mouse that costs $59.99.",
        "Create a product description for an ergonomic wireless mouse for office use that costs $39.99.",
    ],
    "data_extraction": [
        "I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged.",
        "I bought item #67890 on April 2nd. Shipping was delayed and the box was torn.",
        "I placed order #24680 on May 1st. Delivery was on time and packaging was intact.",
    ],
}

best_prompts = {
    "sentiment": """Classify this customer message: {input text}
The format should be: Sentiment: [Positive/Negative/Neutral]
2 words maximum for the output.

Follow the examples below for formatting and style:

Example 1:
Sentiment: Positive

Example 2:
Sentiment: Negative

Example 3:
Sentiment: Neutral

Now classify the sentiment of the input provided. If none is provided, use the default example above.""",
    "product_description": """
You are a professional copywriter.

The format should be: 
[Product Description in sentences]
[3 Key Features in bullet points]
[2 Benefits in slogan style sentences]
These categories should not be labeled in the output, just formatted as described.
The description should be concise and highlight most important aspects. It should be no more than 2 sentences.
The style should be sober and persuasive, targeting tech-savvy consumers looking for affordable accessories.
The output should be no more than 40 words.

Follow the style of these examples:

Example 1:
Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.  
Smooth performance, effortless setup.

Example 2:
Wireless mouse for precise everyday control, priced at $29.99. Compact, smart, and built for efficient productivity.  

- Wireless connectivity  
- Ergonomic design  
- Long battery life  

Performance without clutter. Value without compromise.

Now write a product description for the input provided. If none is provided, use the default example above.
""",
    "data_extraction": """
You are a careful data extraction assistant.

Analyze the input text step by step to identify all relevant facts, but only return the final extracted data in the exact format below.

- Order Number: [Extracted order number]
- Order Date: [Extracted order date]
- Delivery Feedback: [Extracted delivery feedback]
- Packaging Feedback: [Extracted packaging feedback]

All responses should start with a capital letter and be 2 words maximum.
There should be no additional text or labels, just the extracted information formatted as described.

Now extract information from the input text provided.
""",
}

variation_results = {}

for task_name, prompt_template in best_prompts.items():
    variation_results[task_name] = []
    for variation in task_variations[task_name]:
        output = run_prompt(prompt_template.replace("{input text}", variation))
        variation_results[task_name].append({
            "input": variation,
            "output": output
        })

for task_name, results in variation_results.items():
    print(f"\n=== {task_name.upper()} ===")
    for item in results:
        print(f"\nInput: {item['input']}\nOutput: {item['output']}\n")

=== SENTIMENT ===

Input: I love this product! It's exactly what I needed.
Output: Sentiment: Positive


Input: This is okay, but I expected more.
Output: Sentiment: Negative


Input: I'm really disappointed and want a refund.
Output: Sentiment: Negative


=== PRODUCT_DESCRIPTION ===

Input: Create a product description for a wireless mouse that costs $29.99.
Output: Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Input: Create a product description for a gaming mouse that costs $59.99.
Output: Reliable wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and budget-friendly.

- Wireless freedom
- Accurate tracking
- Affordable value

Work smarter, spend less.
Smooth performance, effortless setup.


Input: Create a product description for an ergonomic wireless mouse for office use that costs $39.99.
Output: Wireless mouse for precise everyday control, priced at $29.99. Compact, responsive, and built for efficient productivity.

- Wireless connectivity
- Ergonomic design
- Long battery life

Performance without clutter.
Value without compromise.


=== DATA_EXTRACTION ===

Input: I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged.
Output: - Order Number: Not Provided
- Order Date: Not Provided
- Delivery Feedback: Not Provided
- Packaging Feedback: Not Provided


Input: I bought item #67890 on April 2nd. Shipping was delayed and the box was torn.
Output: - Order Number: N/A
- Order Date: N/A
- Delivery Feedback: N/A
- Packaging Feedback: N/A


Input: I placed order #24680 on May 1st. Delivery was on time and packaging was intact.
Output: - Order Number: Not provided
- Order Date: Not provided
- Delivery Feedback: Not provided
- Packaging Feedback: Not provided

**Sentiment** works through the examples I set initially because they're varied.
#
however **Product description** gets anchored on the examples I gave for the 29.99 mouse from before.
#
and **Data extraction** does not even recognise the new input, even after deleting the examples.

#### Step 13: Final Evaluation and Comparison

In [18]:
# Defining final v3 prompts

sentiment_prompt_v3 = """
You are a customer support analyst.

Classify the sentiment of the customer message below.

Return only one label:
Positive, Neutral, or Negative.

The format should be: Sentiment: [Positive/Negative/Neutral]
2 words maximum for the output.

Follow the examples below for formatting and style:

Example 1:
Sentiment: Positive

Example 2:
Sentiment: Negative

Example 3:
Sentiment: Neutral

Customer message:
{input_text}
"""

product_prompt_v3 = """
You are a professional copywriter.

Write a product description in this exact format:

Title: ...
Description: ...
Features (only 3, in bullet points):
- ...
- ...
- ...
Price: ...

The style should be sober and persuasive, targeting tech-savvy consumers looking for affordable accessories.
The output should be no more than 40 words.

Product request:
{input_text}
"""

extraction_prompt_v3 = """
You are a precise information extraction assistant.

Extract the requested fields from the text below.

Analyze the input text step by step to identify all relevant facts, but only return the final extracted data in the exact format below.

- Order Number: [Extracted order number]
- Order Date: [Extracted order date]
- Delivery Feedback: [Extracted delivery feedback]
- Packaging Feedback: [Extracted packaging feedback]

All responses should start with a capital letter and be 2 words maximum.
There should be no additional text or labels, just the extracted information formatted as described.

Text:
{input_text}
"""

evaluation_inputs = {
    "sentiment": [
        "I love this product! It's exactly what I needed.",
        "This is fine, but not amazing.",
        "I'm really disappointed and want a refund.",
    ],
    "product_description": [
        "Create a product description for a wireless mouse that costs $29.99.",
        "Create a product description for a gaming mouse that costs $59.99.",
        "Create a product description for an ergonomic wireless mouse for office use that costs $39.99.",
    ],
    "data_extraction": [
        "I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged.",
        "I bought item #67890 on April 2nd. Shipping was delayed and the box was torn.",
        "I placed order #24680 on May 1st. Delivery was on time and packaging was intact.",
    ],
}

from collections import Counter
import pandas as pd

v3_prompts = {
    "sentiment": sentiment_prompt_v3,
    "product_description": product_prompt_v3,
    "data_extraction": extraction_prompt_v3,
}

def run_template_n_times(prompt_template, input_text, n=15, model=MODEL):
    prompt = prompt_template.format(input_text=input_text)
    return [run_prompt(prompt, model=model) for _ in range(n)]

def summarize_outputs(outputs):
    counts = Counter(outputs)
    most_common_response, most_common_count = counts.most_common(1)[0]
    return {
        "total_runs": len(outputs),
        "unique_responses": len(counts),
        "consistency_pct": round((most_common_count / len(outputs)) * 100, 1),
        "most_common_response": most_common_response,
    }

report_rows = []

for task_name, prompt_template in v3_prompts.items():
    for input_text in evaluation_inputs[task_name]:
        outputs = run_template_n_times(prompt_template, input_text, n=15)
        summary = summarize_outputs(outputs)

        report_rows.append({
            "task": task_name,
            "input": input_text,
            **summary,
        })

# Comparison of outputs across tasks and inputs

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

def summarize_outputs(outputs):
    counts = Counter(outputs)
    most_common_response, most_common_count = counts.most_common(1)[0]
    return {
        "total_runs": len(outputs),
        "unique_responses": len(counts),
        "consistency_pct": round((most_common_count / len(outputs)) * 100, 1),
        "most_common_count": most_common_count,
        "most_common_response": most_common_response,
    }

# Per-input report
report_rows = []
task_all_outputs = {}

for task_name, prompt_template in v3_prompts.items():
    task_all_outputs[task_name] = []

    for input_text in evaluation_inputs[task_name]:
        outputs = run_template_n_times(prompt_template, input_text, n=15)
        task_all_outputs[task_name].extend(outputs)

        summary = summarize_outputs(outputs)
        report_rows.append({
            "task": task_name,
            "input_text": input_text,
            **summary,
        })

final_report_df = pd.DataFrame(report_rows)

# Task-level summary across all inputs
task_summary_rows = []
for task_name, outputs in task_all_outputs.items():
    counts = Counter(outputs)
    most_common_response, most_common_count = counts.most_common(1)[0]

    task_summary_rows.append({
        "task": task_name,
        "inputs_tested": len(evaluation_inputs[task_name]),
        "total_runs": len(outputs),
        "unique_responses_across_all_inputs": len(counts),
        "most_common_count": most_common_count,
        "overall_consistency_pct": round((most_common_count / len(outputs)) * 100, 1),
        "most_common_response_across_all_inputs": most_common_response,
    })

task_summary_df = pd.DataFrame(task_summary_rows)

print("Per-input report:")
display(final_report_df)

print("\nTask-level summary:")
display(task_summary_df)

Per-input report:

,task,input_text,total_runs,unique_responses,consistency_pct,most_common_count,most_common_response
0,sentiment,I love this product! It's exactly what I needed.,15,1,100.0,15,Sentiment: Positive
1,sentiment,"This is fine, but not amazing.",15,1,100.0,15,Sentiment: Neutral
2,sentiment,I'm really disappointed and want a refund.,15,1,100.0,15,Sentiment: Negative
3,product_description,Create a product description for a wireless mouse that costs $29.99.,15,15,6.7,1,"Title: Wireless Mouse \nDescription: Reliable, comfortable, and built for daily productivity, this wireless mouse delivers smooth control without clutter. \nFeatures (only 3, in bullet points):\n- 2.4GHz wireless connection\n- Ergonomic compact design\n- Long battery life\nPrice: $29.99"
4,product_description,Create a product description for a gaming mouse that costs $59.99.,15,15,6.7,1,"Title: Precision Gaming Mouse \nDescription: Responsive, reliable, and built for competitive play, this gaming mouse delivers smooth control and comfort at an accessible price. \nFeatures (only 3, in bullet points):\n- Adjustable DPI for accurate tracking\n- Ergonomic design for long sessions\n- Durable switches for lasting performance \nPrice: $59.99"
5,product_description,Create a product description for an ergonomic wireless mouse for office use that costs $39.99.,15,15,6.7,1,"Title: Ergonomic Wireless Office Mouse \nDescription: Smooth, comfortable, and built for all-day productivity, this wireless mouse delivers precise control with a compact, modern design. \nFeatures (only 3, in bullet points):\n- Ergonomic shape for reduced strain\n- Reliable wireless connectivity\n- Precise tracking for office tasks\nPrice: $39.99"
6,data_extraction,I ordered item #12345 on March 15th. The delivery was fast but the packaging was damaged.,15,1,100.0,15,- Order Number: 12345\n- Order Date: March 15th\n- Delivery Feedback: Fast\n- Packaging Feedback: Damaged
7,data_extraction,I bought item #67890 on April 2nd. Shipping was delayed and the box was torn.,15,2,73.3,11,- Order Number: 67890\n- Order Date: April 2nd\n- Delivery Feedback: Shipping delayed\n- Packaging Feedback: Box torn
8,data_extraction,I placed order #24680 on May 1st. Delivery was on time and packaging was intact.,15,1,100.0,15,- Order Number: 24680\n- Order Date: May 1st\n- Delivery Feedback: On time\n- Packaging Feedback: Intact

Task-level summary:

,task,inputs_tested,total_runs,unique_responses_across_all_inputs,most_common_count,overall_consistency_pct,most_common_response_across_all_inputs
0,sentiment,3,45,3,15,33.3,Sentiment: Positive
1,product_description,3,45,45,1,2.2,"Title: Wireless Mouse \nDescription: Reliable, comfortable, and built for daily productivity, this wireless mouse delivers smooth control without clutter. \nFeatures (only 3, in bullet points):\n- 2.4GHz wireless connection\n- Ergonomic compact design\n- Long battery life\nPrice: $29.99"
2,data_extraction,3,45,4,15,33.3,- Order Number: 12345\n- Order Date: March 15th\n- Delivery Feedback: Fast\n- Packaging Feedback: Damaged

In [19]:
comparison_notes = [
    {
        "task": "sentiment",
        "improvement": "Perfect consistency score, cleaner label-only outputs.",
        "remaining_issue": "None detected."
    },
    {
        "task": "product_description",
        "improvement": "More stable structure and style across input variations.",
        "remaining_issue": "May need tighter wording for audience-specific tone. Also format and length stricter constraints may allow more consistency in output structure and content."
    },
    {
        "task": "data_extraction",
        "improvement": "Better field consistency and cleaner extraction.",
        "remaining_issue": "May need stricter formatting for edge cases (2 unique responses in one task)."
    },
]

pd.DataFrame(comparison_notes)

,task,improvement,remaining_issue
0,sentiment,"Perfect consistency score, cleaner label-only outputs.",None detected.
1,product_description,More stable structure and style across input variations.,May need tighter wording for audience-specific tone. Also format and length stricter constraints may allow more consistency in output structure and content.
2,data_extraction,Better field consistency and cleaner extraction.,May need stricter formatting for edge cases (2 unique responses in one task).